[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"

[theme]
primaryColor = "#C5210D"
backgroundColor = "#D9D9D9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#20201D"
font = "sans serif"
